site_name: idNINE | ArtTech Notes
theme:
  name: material
  repo_url: https://idnine.ghost.io
  repo_name: idNINE Home
  icon:
    repo: material/web
  features:
    # - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.critic:
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.keys
  - pymdownx.tilde

extra:
  social:
    - icon: material/web
      link: https://idnine.ghost.io
      name: idNINE Home
    - icon: simple/instagram
      link: https://www.instagram.com/idnine_design/
  analytics:
    provider: google
    property: G-SQBKE2MSJ2

copyright: &copy; 2026 idNINE(JongHoe Koo). All rights reserved.
