site_name: idNINE | ArtTech Notes
theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.critic:
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.keys
  - pymdownx.tilde

extra:
  social:
    - icon: simple/homepage
      link: https://idnine.kr
    - icon: simple/instagram
      link: https://www.instagram.com/idnine_design/

copyright: Copyright &copy; 2026 JongHoe Koo @idnine. All rights reserved.
