name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push가 일어날 때 작동합니다. (master인 경우 변경 필요)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          # 만약 다른 플러그인을 쓰신다면 여기에 추가로 적어줍니다.

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          mkdocs gh-deploy --force
